 interface RootLayoutprops{children: React.ReactNode;};
import type { Metadata } from "next";
import "@/styles/globals.css";
import { Cairo } from "next/font/google";
import Navbar from "@/components/header/Navbar";
import Footer from "@/components/footer";
import HeaderSlider from "@/components/header/HeaderSlider";


const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin"],
});





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<RootLayoutprops>) {
  return (
    <html lang="en">
      <body className={cairo.className}>
          <Navbar />
        <section className="section">
         
      <main className="fixed-bottom-0 left-0  top-0" >{children}</main>
      {/* Allow footer to push down */}
        <Footer />
        </section>
        
       
    

      </body>


    </html>
  );
}
